services:
  krona:
    build:
      args:
        http_proxy: http://172.19.75.255:7897
        https_proxy: http://172.19.75.255:7897
      context: .
      dockerfile: Dockerfile
    image: shuai/krona:2.8.1
    container_name: krona
    # tty: true
    # stdin_open: true
    # entrypoint: ["ktImportTaxonomy"]
    command:
      [
        "ktImportTaxonomy",
        "-o",
        "/ResultData/m11216.report.html",
        "/ResultData/m11216.report.txt",
      ]
    volumes:
      - /media/shuai/TOSHBA/mm-dev/RawData:/RawData
      - /media/shuai/TOSHBA/mm-dev/ResultData:/ResultData
      - /media/shuai/TOSHBA/mm-dev/ManualData:/ManualData
      - /media/shuai/TOSHBA/mm-dev/ReferenceData:/ReferenceData
    user: "1000:1000"
    environment:
      - COMPOSE_PARALLEL_LIMIT=16
volumes:
  RawData:
    driver: local
  ResultData:
    driver: local
  ManualData:
    driver: local
  ReferenceData:
    driver: local
