services:
  combined_analysis:
    build:
      context: .
      dockerfile: Dockerfile
    image: shuai/r_combined_analysis:1.0
    container_name: r_analysis_container
    # tty: true
    # stdin_open: true
    command: [ "combined_analysis.R", "--help" ]
    volumes:
      - /media/shuai/TOSHBA/mm-dev/RawData:/RawData
      - /media/shuai/TOSHBA/mm-dev/ResultData:/ResultData
      - /media/shuai/TOSHBA/mm-dev/ManualData:/ManualData
      - /media/shuai/TOSHBA/mm-dev/ReferenceData:/ReferenceData
volumes:
  RawData:
    driver: local
  ResultData:
    driver: local
  ManualData:
    driver: local
  ReferenceData:
    driver: local
