services:
  krona:
    build:
      context: .
      dockerfile: Dockerfile
    image: shuai/krona:1.0
    container_name: krona
    # tty: true
    # stdin_open: true
    command: ["ktImportTaxonomy", "--help"] 
    volumes:
      - /media/shuai/TOSHBA/mm-dev/RawData:/RawData
      - /media/shuai/TOSHBA/mm-dev/ResultData:/ResultData
      - /media/shuai/TOSHBA/mm-dev/ManualData:/ManualData
      - /media/shuai/TOSHBA/mm-dev/ReferenceData:/ReferenceData
volumes:
  RawData:
    driver: local
  ResultData:
    driver: local
  ManualData:
    driver: local
  ReferenceData:
    driver: local
