services:
  krona:
    # args:
    #   - http_proxy=http://172.19.11.241:443
    #   - https_proxy=http://172.19.11.241:443
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    image: krona
    container_name: krona_container
    command: ktImportTaxonomy
    volumes:
      - /media/shuai/TOSHBA/mm-dev/RawData:/RawData
      - /media/shuai/TOSHBA/mm-dev/ResultData:/ResultData
      - /media/shuai/TOSHBA/mm-dev/ManualData:/ManualData
      - /media/shuai/TOSHBA/mm-dev/ReferenceData:/ReferenceData
volumes:
  RawData:
    driver: local
  ResultData:
    driver: local
  ManualData:
    driver: local
  ReferenceData:
    driver: local
