services:
  qiime2:
    image: quay.io/qiime2/metagenome:2024.5
    container_name: qiime2
    # tty: true
    # stdin_open: true
    # 3-去除低丰度特征：去除低丰度的分类单元，减少噪声的影响。
    command:
      [
        "qiime",
        "feature-table",
        "filter-features",
        "--i-table",
        "/ResultData/feature-table.qza",
        "--p-min-frequency",
        "10",
        "--o-filtered-table",
        "/ResultData/filtered-table.qza"
      ]
    volumes:
      - /media/shuai/TOSHBA/mm-dev/RawData:/RawData
      - /media/shuai/TOSHBA/mm-dev/ResultData:/ResultData
      - /media/shuai/TOSHBA/mm-dev/ManualData:/ManualData
      - /media/shuai/TOSHBA/mm-dev/ReferenceData:/ReferenceData
    user: "1000:1000" # 使用主机用户的 UID 和 GID
    # environment:
    #   - COMPOSE_PARALLEL_LIMIT=16
volumes:
  RawData:
    driver: local
  ResultData:
    driver: local
  ManualData:
    driver: local
  ReferenceData:
    driver: local
