services:
  qiime2:
    image: quay.io/qiime2/metagenome:2024.5
    container_name: qiime2
    # tty: true
    # stdin_open: true
    # 使用如ANCOM的工具来识别组间差异显著的分类单元。
    command:
      [
        "qiime",
        "composition",
        "add-pseudocount",
        "--i-table",
        "/ResultData/final-table.qza",
        "--o-composition-table",
        "/ResultData/comp-table.qza"
      ]
    volumes:
      - /media/shuai/TOSHBA/mm-dev/RawData:/RawData
      - /media/shuai/TOSHBA/mm-dev/ResultData:/ResultData
      - /media/shuai/TOSHBA/mm-dev/ManualData:/ManualData
      - /media/shuai/TOSHBA/mm-dev/ReferenceData:/ReferenceData
    user: "1000:1000" # 使用主机用户的 UID 和 GID
    # environment:
    #   - COMPOSE_PARALLEL_LIMIT=16
volumes:
  RawData:
    driver: local
  ResultData:
    driver: local
  ManualData:
    driver: local
  ReferenceData:
    driver: local
