services:
  phyloseq:
    image: quay.io/biocontainers/bioconductor-phyloseq:1.46.0--r43hdfd78af_0
    container_name: phyloseq-2
    tty: true
    stdin_open: true
    command:
      [
        "bash",
      ]
    volumes:
      - /media/shuai/TOSHBA/mm-dev/RawData:/RawData
      - /media/shuai/TOSHBA/mm-dev/ResultData:/ResultData
      - /media/shuai/TOSHBA/mm-dev/ManualData:/ManualData
      - /media/shuai/TOSHBA/mm-dev/ReferenceData:/ReferenceData
    working_dir: /
    user: "1000:1000"
    restart: no  
volumes:
  RawData:
    driver: local
  ResultData:
    driver: local
  ManualData:
    driver: local
  ReferenceData:
    driver: local
