services:
  krona:
    image: quay.io/qiime2/metagenome:2024.5
    container_name: qiime2
    # tty: true
    # stdin_open: true
    #去除低丰度特征：去除低丰度的分类单元，减少噪声的影响。
    command:
      [
        "qiime",
        "composition",
        "ancom",
        "--i-table",
        "/ResultData/comp-table.qza",
        "--m-metadata-file",
        "/ResultData/sample_metadata.tsv",
        "--m-metadata-column",
        "treatment",
        "--o-visualization",
        "/ResultData/ancom-treatments.qzv"
      ]
    volumes:
      - /media/shuai/TOSHBA/mm-dev/RawData:/RawData
      - /media/shuai/TOSHBA/mm-dev/ResultData:/ResultData
      - /media/shuai/TOSHBA/mm-dev/ManualData:/ManualData
      - /media/shuai/TOSHBA/mm-dev/ReferenceData:/ReferenceData
      - /tmp:/tmp
    user: "1000:1000" # 使用主机用户的 UID 和 GID
    # environment:
    #   - COMPOSE_PARALLEL_LIMIT=16
volumes:
  RawData:
    driver: local
  ResultData:
    driver: local
  ManualData:
    driver: local
  ReferenceData:
    driver: local
  tmp:
    driver: local
