services:
  kraken2:
    build:
      context: .
      dockerfile: Dockerfile
    image: shuai/kraken2:3.12
    container_name: kraken2
    # tty: true
    # stdin_open: true
    command: [ "kraken2", "--help" ]
    volumes:
      - /media/shuai/TOSHBA/mm-dev/RawData:/RawData
      - /media/shuai/TOSHBA/mm-dev/ResultData:/ResultData
      - /media/shuai/TOSHBA/mm-dev/ManualData:/ManualData
      - /media/shuai/TOSHBA/mm-dev/ReferenceData:/ReferenceData
volumes:
  RawData:
    driver: local
  ResultData:
    driver: local
  ManualData:
    driver: local
  ReferenceData:
    driver: local
